import { expect, test } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import {
  githubFixtureCompletedSteps,
  githubFixtureProjectData,
} from "./github-markdown-fixture-data";

const workspaceKey = "cgpt-workspace";
const githubFixturePath = fileURLToPath(
  new URL("./fixtures/github-markdown-fixture.v1.md", import.meta.url),
);
const generatedDateLine =
  /^\*Generated by The OverKill Hill Found-Ry · OKH P³ · \d{4}-\d{2}-\d{2}\*$/m;
const fixturePreviewEnabled =
  process.env.GITHUB_MARKDOWN_FIXTURE_PREVIEW === "1";
const fixtureRefreshEnabled =
  process.env.GITHUB_MARKDOWN_FIXTURE_REFRESH === "1";

function preserveCommittedGeneratedDate(
  generatedMarkdown: string,
  committedMarkdown: string,
): string {
  const committedDate = committedMarkdown.match(generatedDateLine)?.[0];
  if (!committedDate) {
    throw new Error("Committed GitHub fixture is missing the expected generated-date line");
  }
  if (!generatedDateLine.test(generatedMarkdown)) {
    throw new Error("Creator export is missing the expected generated-date line");
  }
  return generatedMarkdown.replace(generatedDateLine, committedDate);
}

function summarizeFixtureDiff(
  generatedMarkdown: string,
  committedMarkdown: string,
  refreshedMarkdown: string,
): string {
  if (refreshedMarkdown === committedMarkdown) {
    if (generatedMarkdown === committedMarkdown) {
      return "Fixture preview: no changes.";
    }

    const beforeMetadata = committedMarkdown.match(generatedDateLine)?.[0];
    const afterMetadata = generatedMarkdown.match(generatedDateLine)?.[0];
    return [
      "Fixture preview: generated metadata only; export content is unchanged.",
      `- ${beforeMetadata}`,
      `+ ${afterMetadata}`,
      "The refresh command preserves the committed generated-date line, so it would not modify the fixture.",
    ].join("\n");
  }

  const committedLines = committedMarkdown.split("\n");
  const refreshedLines = refreshedMarkdown.split("\n");
  const changedLineIndexes = Array.from(
    { length: Math.max(committedLines.length, refreshedLines.length) },
    (_, index) => index,
  ).filter((index) => committedLines[index] !== refreshedLines[index]);
  const firstChangedLine = changedLineIndexes[0];
  const before = committedLines[firstChangedLine] ?? "<end of file>";
  const after = refreshedLines[firstChangedLine] ?? "<end of file>";

  return [
    "Fixture preview: export content changes detected.",
    `${changedLineIndexes.length} line position(s) differ; first difference at line ${firstChangedLine + 1}:`,
    `- ${before}`,
    `+ ${after}`,
    "Run the refresh command to write and verify the fixture.",
  ].join("\n");
}

test("classifies generated-date drift as metadata only", () => {
  const committed =
    "# Fixture\n\n*Generated by The OverKill Hill Found-Ry · OKH P³ · 2026-01-01*\n\nContent";
  const generated = committed.replace("2026-01-01", "2026-09-17");
  const refreshed = preserveCommittedGeneratedDate(generated, committed);

  expect(summarizeFixtureDiff(generated, committed, refreshed)).toContain(
    "generated metadata only; export content is unchanged",
  );
});

test("shows the first before/after line for export content changes", () => {
  const committed =
    "# Fixture\n\n*Generated by The OverKill Hill Found-Ry · OKH P³ · 2026-01-01*\n\nBefore";
  const generated =
    "# Fixture\n\n*Generated by The OverKill Hill Found-Ry · OKH P³ · 2026-09-17*\n\nAfter";
  const refreshed = preserveCommittedGeneratedDate(generated, committed);
  const summary = summarizeFixtureDiff(generated, committed, refreshed);

  expect(summary).toContain("export content changes detected");
  expect(summary).toContain("- Before");
  expect(summary).toContain("+ After");
});

test.skip(
  !fixturePreviewEnabled && !fixtureRefreshEnabled,
  "Fixture preview and refresh are disabled by default; use a package command to opt in.",
);

test("previews or refreshes the committed GitHub fixture from the Creator export", async ({
  page,
}) => {
  await page.goto("./#creator");
  await page.evaluate(
    ({ data, completedSteps, key }) => {
      localStorage.clear();
      const id = "project-test";
      localStorage.setItem(
        key,
        JSON.stringify({
          version: 1,
          activeProjectId: id,
          projects: [
            {
              id,
              name: "Test GPT",
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
              archived: false,
              data,
              completedSteps,
              currentPage: 0,
              sidebarOpen: true,
            },
          ],
        }),
      );
    },
    {
      data: githubFixtureProjectData,
      completedSteps: githubFixtureCompletedSteps,
      key: workspaceKey,
    },
  );
  await page.reload();
  await page.getByRole("button", { name: "Export Package" }).click();
  await expect(page.locator("h1")).toContainText("Export Package");

  const generatedMarkdown = await page.locator("pre").innerText();
  const committedMarkdown = await readFile(githubFixturePath, "utf8");
  const refreshedMarkdown = preserveCommittedGeneratedDate(
    generatedMarkdown,
    committedMarkdown,
  );

  // The refresh intentionally retains the committed date so running this command
  // on another calendar date changes bytes only when exporter behavior changes.
  const anotherDateExport = generatedMarkdown.replace(
    generatedDateLine,
    "*Generated by The OverKill Hill Found-Ry · OKH P³ · 2099-12-31*",
  );
  expect(
    preserveCommittedGeneratedDate(anotherDateExport, committedMarkdown),
  ).toBe(refreshedMarkdown);

  console.log(
    summarizeFixtureDiff(
      generatedMarkdown,
      committedMarkdown,
      refreshedMarkdown,
    ),
  );

  if (fixturePreviewEnabled) {
    await expect(readFile(githubFixturePath, "utf8")).resolves.toBe(
      committedMarkdown,
    );
    return;
  }

  const refreshedBytes = Buffer.from(refreshedMarkdown, "utf8");
  await writeFile(githubFixturePath, refreshedBytes);
  await expect(readFile(githubFixturePath)).resolves.toEqual(refreshedBytes);
});
