import { useState, useCallback } from "react";
import { BUILD_STEPS, INSTRUCTION_LAYERS } from "../data/knowledge";

const CREATOR_STATE_KEY = "cgpt-creator-state";

function loadCompletedSteps(): Set<number> {
  try {
    const saved = JSON.parse(localStorage.getItem(CREATOR_STATE_KEY) || "{}") as {
      completedSteps?: unknown;
    };
    return new Set(
      Array.isArray(saved.completedSteps)
        ? saved.completedSteps.filter(
            (step): step is number =>
              typeof step === "number" && Number.isInteger(step) && step >= 0 && step < BUILD_STEPS.length,
          )
        : [],
    );
  } catch {
    return new Set();
  }
}

function loadStep(key: string) {
  try { return JSON.parse(localStorage.getItem(key) || "{}"); }
  catch { return {}; }
}

function buildMarkdown(): string {
  const brief = loadStep("cgpt-step-0");
  const contract = loadStep("cgpt-step-1");
  const layerData = loadStep("cgpt-step-2");
  const knowledge = loadStep("cgpt-step-3");
  const caps = loadStep("cgpt-step-4");
  const capsRationale = loadStep("cgpt-step-4-rationale");
  const actions = loadStep("cgpt-step-5");
  const savedStarters = loadStep("cgpt-step-6");
  const starters: string[] = Array.isArray(savedStarters) ? savedStarters : [];
  const tests = loadStep("cgpt-step-7");
  const ship = loadStep("cgpt-step-8");

  const instructionBlock = INSTRUCTION_LAYERS
    .map(l => layerData[l.id] ? `### Layer ${l.id}: ${l.label}\n${layerData[l.id]}` : "")
    .filter(Boolean)
    .join("\n\n");

  return `# Custom GPT Specification Package
*Generated by The OverKill Hill Found-Ry · OKH P³ · ${new Date().toISOString().split("T")[0]}*

---

## 0. Build Brief

**GPT Name:** ${brief.gptName || "(not set)"}
**Primary Users:** ${brief.primaryUsers || "(not set)"}
**Version:** ${ship.currentVersion || "v0.1"}
**Owner:** ${ship.ownerName || "(not set)"}
**Visibility:** ${ship.visibility || "(not set)"}

### Primary Outcomes
${brief.outcomes || "(not defined)"}

### Non-Goals / Out of Scope
${brief.nonGoals || "(not defined)"}

### Done-When Acceptance Criteria
${brief.doneCriteria || "(not defined)"}

### Data Sources
- **Allowed:** ${brief.allowedSources || "(not set)"}
- **Disallowed:** ${brief.disallowedSources || "(not set)"}

### Tooling & Compliance
- **Tooling:** ${brief.toolingAllowed || "(not set)"}
- **Compliance:** ${brief.compliance || "(not set)"}

---

## 1. Conversation Contract

### Inputs
${contract.inputs || "(not defined)"}

### Outputs
${contract.outputs || "(not defined)"}

### Top Tasks (ranked)
${contract.topTasks || "(not defined)"}

### Catastrophic Mistakes
${contract.catastrophicMistakes || "(not defined)"}

---

## 2. Instructions

${instructionBlock || "(no instruction layers filled)"}

---

## 3. Knowledge Files

${knowledge.files && knowledge.files.length > 0
  ? knowledge.files.map((f: { filename: string; type: string; topic: string; notes: string }, i: number) =>
      `${i + 1}. \`${f.filename || "(unnamed)"}\` [${f.type}] — ${f.topic || "(no topic)"}${f.notes ? `\n   *Routing note: ${f.notes}*` : ""}`
    ).join("\n")
  : "(no files planned)"}

${knowledge.retrievalNotes ? `**Retrieval notes:**\n${knowledge.retrievalNotes}` : ""}

---

## 4. Capabilities

${Object.entries(caps || {}).filter(([, v]) => v).map(([k]) => `- ✓ ${k}`).join("\n") || "(no capabilities configured)"}

---

## 5. Actions / Apps

**Choice:** ${actions.choice || "none"}
${actions.choice === "actions" ? `**Auth type:** ${actions.authType || "none"}
**Privacy Policy URL:** ${actions.privacyPolicyUrl || "(not set)"}
${actions.errorHandling ? `**Error handling:** ${actions.errorHandling}` : ""}` : ""}
${actions.choice === "apps" ? `**Apps notes:** ${actions.appsNotes || "(none)"}` : ""}

---

## 6. Conversation Starters

${starters.filter((s: string) => s.trim()).map((s: string, i: number) => `${i + 1}. "${s}"`).join("\n") || "(no starters written)"}

---

## 7. Test Matrix

${tests.cases && tests.cases.length > 0
  ? tests.cases.map((c: { category: string; prompt: string; expectedBehavior: string; result: string }, i: number) =>
      `**T${i + 1}** [${c.category}] ${c.result === "pass" ? "✓" : c.result === "fail" ? "✗" : "○"}\n- Prompt: ${c.prompt || "(empty)"}\n- Expected: ${c.expectedBehavior || "(not set)"}`
    ).join("\n\n")
  : "(no test cases defined)"}

---

## 8. Governance

**Visibility:** ${ship.visibility || "(not set)"}
**Version:** ${ship.currentVersion || "(not set)"}
**Owner:** ${ship.ownerName || "(not set)"}
**Scheduled review:** ${ship.scheduledReview || "(not set)"}

### Change Log
${ship.changeLog || "(no changelog entry)"}

### Maintenance Cadence
${ship.maintenanceCadence || "(not defined)"}

---

*This spec was built using the okhp3-custom-gpt-builder Agent Skill v1.0.0 · Apache-2.0*
*Source: https://github.com/OKHP3/OverKill-Hill-FoundRy*
`;
}

export default function ExportPackage({ completedSteps: liveCompletedSteps }: { completedSteps?: Set<number> }) {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<"markdown" | "instructions">("markdown");
  const [storedCompletedSteps] = useState(loadCompletedSteps);
  const completedSteps = liveCompletedSteps ?? storedCompletedSteps;
  const incompleteSteps = BUILD_STEPS.filter(({ id }) => !completedSteps.has(id));

  const fullMarkdown = buildMarkdown();

  const instructionsOnly = (() => {
    const layerData = loadStep("cgpt-step-2");
    return INSTRUCTION_LAYERS
      .map(l => layerData[l.id] ? `## ${l.label}\n${layerData[l.id]}` : "")
      .filter(Boolean)
      .join("\n\n");
  })();

  const content = format === "markdown" ? fullMarkdown : instructionsOnly;

  const copy = useCallback(async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true); setTimeout(() => setCopied(false), 2000);
  }, [content]);

  const download = () => {
    const brief = loadStep("cgpt-step-0");
    const name = (brief.gptName || "custom-gpt").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${name}-spec.md`; a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ maxWidth: 900, margin: "0 auto" }}>
      <div style={{ marginBottom: "1.5rem" }}>
        <h1 style={{ fontFamily: "var(--font-heading)", fontSize: "1.5rem", color: "var(--color-forge-accent)", margin: 0 }}>
          📦 Export Package
        </h1>
        <p style={{ color: "var(--color-forge-muted-fg)", marginTop: "0.35rem", fontSize: "0.9rem" }}>
          Copy or download your complete GPT specification package. This is your source-of-truth artifact.
        </p>
      </div>

      {incompleteSteps.length > 0 && (
        <div
          role="alert"
          style={{
            marginBottom: "1rem",
            padding: "1rem 1.1rem",
            background: "color-mix(in srgb, var(--color-forge-accent) 10%, var(--color-forge-panel))",
            border: "1px solid var(--color-forge-accent)",
            borderRadius: "var(--radius-md)",
            color: "var(--color-forge-fg)",
          }}
        >
          <strong style={{ display: "block", color: "var(--color-forge-accent)", marginBottom: "0.35rem" }}>
            ⚠️ This package is not complete yet
          </strong>
          <span style={{ display: "block", color: "var(--color-forge-muted-fg)", fontSize: "0.85rem", marginBottom: "0.65rem" }}>
            You can still export, but these required build steps are incomplete:
          </span>
          <ul style={{ display: "grid", gap: "0.3rem", margin: 0, paddingLeft: "1.25rem", fontSize: "0.85rem" }}>
            {incompleteSteps.map(({ id, label }) => (
              <li key={id}>{label}</li>
            ))}
          </ul>
        </div>
      )}

      <div style={{ display: "flex", gap: "0.75rem", marginBottom: "1rem", alignItems: "center" }}>
        <div style={{ display: "flex", gap: "0.5rem" }}>
          {(["markdown", "instructions"] as const).map(f => (
            <button key={f} onClick={() => setFormat(f)}
              style={{
                padding: "0.4rem 0.75rem", borderRadius: "var(--radius-md)", cursor: "pointer",
                background: format === f ? "var(--color-forge-accent)" : "var(--color-forge-panel)",
                color: format === f ? "var(--color-forge-paper)" : "var(--color-forge-fg)",
                border: "1px solid var(--color-forge-border)", fontFamily: "var(--font-body)", fontSize: "0.82rem",
              }}>
              {f === "markdown" ? "Full Spec (Markdown)" : "Instructions Only"}
            </button>
          ))}
        </div>
        <div style={{ marginLeft: "auto", display: "flex", gap: "0.5rem" }}>
          <button onClick={copy} style={primaryBtn}>{copied ? "✓ Copied!" : "📋 Copy"}</button>
          <button onClick={download} style={secondaryBtn}>⬇ Download .md</button>
        </div>
      </div>

      <pre style={{
        background: "var(--color-forge-espresso)", border: "1px solid var(--color-forge-border)",
        borderRadius: "var(--radius-md)", padding: "1.25rem",
        fontFamily: "var(--font-mono)", fontSize: "0.78rem", lineHeight: 1.7,
        color: "var(--color-forge-fg)", whiteSpace: "pre-wrap",
        maxHeight: "calc(100vh - 280px)", overflowY: "auto",
      }}>
        {content}
      </pre>

      <div style={{ marginTop: "1rem", padding: "0.75rem 1rem", background: "var(--color-forge-panel)", border: "1px solid var(--color-forge-border)", borderRadius: "var(--radius-md)", fontSize: "0.8rem", color: "var(--color-forge-muted-fg)" }}>
        💡 <strong>Usage:</strong> The "Full Spec" is your version-controlled source of truth — keep it in your repo alongside the GPT. The "Instructions Only" view is ready to paste directly into the ChatGPT builder's Instructions field.
      </div>
    </div>
  );
}

const primaryBtn: React.CSSProperties = {
  background: "var(--color-forge-accent)", color: "var(--color-forge-paper)",
  border: "none", borderRadius: "var(--radius-md)", padding: "0.5rem 1rem",
  fontFamily: "var(--font-body)", fontSize: "0.85rem", cursor: "pointer", fontWeight: 600,
};
const secondaryBtn: React.CSSProperties = {
  background: "var(--color-forge-panel)", color: "var(--color-forge-fg)",
  border: "1px solid var(--color-forge-border)", borderRadius: "var(--radius-md)", padding: "0.5rem 1rem",
  fontFamily: "var(--font-body)", fontSize: "0.85rem", cursor: "pointer",
};
