import assert from "node:assert/strict";
import vm from "node:vm";
import { readFile } from "node:fs/promises";
import { parseCapabilityBackup } from "../../../artifacts/mockup-sandbox/src/lib/capability-workbench.ts";

const backup = await readFile(new URL("./generated/backup.json", import.meta.url), "utf8");
const workspace = parseCapabilityBackup(backup);
assert.equal(workspace.projects[0].kind, "software");
const html = await readFile(new URL("./generated/app/index.html", import.meta.url), "utf8");
const input = { value: "" };
const output = { textContent: "" };
const button = { addEventListener: (event, handler) => { assert.equal(event, "click"); button.click = handler; } };
const document = { querySelector: (selector) => selector === "#input" ? input : selector === "#output" ? output : button };
const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert.ok(script, "generated starter script exists");
vm.runInNewContext(script, { document });
input.value = '{"count":3,"tags":["a"],"missing":null}';
button.click();
const valid = JSON.parse(output.textContent);
assert.deepEqual(valid.fields, { count: "number", tags: "array", missing: "null" });
input.value = "{broken";
button.click();
assert.equal(JSON.parse(output.textContent).validJson, false);
const hostile = '</textarea><script>window.injected=true</script> <img src=x onerror=alert(1)>';
input.value = JSON.stringify({ name: hostile });
button.click();
assert.equal(valid.validJson, true);
assert.equal((html.match(/<script/gi) ?? []).length, 2, "hostile name does not create a script tag");
console.log("software example smoke: backup, valid, invalid, hostile cases passed in Node runtime");
